#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -eu

properties_file=$1

mkdir -p $(dirname ${properties_file})

cat > ${properties_file} <<EOF
build.time=$(date -u +'%Y-%m-%d %H:%M:%S %Z')
build.date=$(date +'%a %Y-%m-%d')
build.machine=$(hostname -f)
build.path=$PWD
build.user.name=$USER
EOF

if [ -d $(dirname ${properties_file})/../../.git ]; then
cat >> ${properties_file} <<EOF
build.git.revision=$(git rev-parse HEAD)
build.git.tag=$(git describe --dirty --always)
EOF
fi
